version: "3"

networks:
  rinha-2024:
    external: true

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-backend-1
      - rinha-backend-2
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    networks:
      - rinha-2024
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "10MB"

  rinha-backend-1: 
    build: .
    image: rinha_backend
    container_name: rinha-backend-1
    environment:
      - DB_HOSTNAME=db
      - API_SERVER_LISTEN=:8081
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - rinha-2024
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  rinha-backend-2:
    image: rinha_backend
    container_name: rinha-backend-2
    environment:
      - DB_HOSTNAME=db
      - API_SERVER_LISTEN=:8082
    ports:
      - "8082:8082"
    depends_on:
      - rinha-backend-1
      - db
    networks:
      - rinha-2024
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5431:5432"
    volumes:
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - rinha-2024
    deploy:
      resources:
        limits:
          # Note que a soma de todos os limites dos serviços
          # aqui declarados é de 1.5 unidades de CPU e 550MB
          # de memória. A distribuição feita aqui é apenas
          # um exemplo – distribua como quiser.
          cpus: "0.2"
          memory: "140MB"

