version: "3"

networks:
  rinha2024q1:
    external: true

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rinha-backend-1
      - rinha-backend-2
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    networks:
      - rinha2024q1
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "140MB"

  rinha-backend-1: 
    image: italobbarros/rinha-backend-2024-q1:latest
    container_name: rinha-backend-2024-q1-1
    environment:
      - DB_HOSTNAME=db
      - API_SERVER_LISTEN=0.0.0.0:8081
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - rinha2024q1
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "170MB"

  rinha-backend-2:
    image: italobbarros/rinha-backend-2024-q1:latest
    container_name: rinha-backend-2024-q1-2
    environment:
      - DB_HOSTNAME=db
      - API_SERVER_LISTEN=0.0.0.0:8082
    ports:
      - "8082:8082"
    depends_on:
      - rinha-backend-1
      - db
    networks:
      - rinha2024q1
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "170MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5431:5432"
    volumes:
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./sql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - rinha2024q1
    deploy:
      resources:
        limits:
          # Note que a soma de todos os limites dos serviços
          # aqui declarados é de 1.5 unidades de CPU e 550MB
          # de memória. A distribuição feita aqui é apenas
          # um exemplo – distribua como quiser.
          cpus: "0.4"
          memory: "70MB"

