version: "3"

networks:
  rinha2024q1:
    external: true

services:
  rinha-backend-1: 
    build: .
    image: rinha-backend
    container_name: rinha-backend-1
    environment:
      - DB_HOSTNAME=db
      - API_SERVER_LISTEN=0.0.0.0:8081
    ports:
      - "9999:8081"
    depends_on:
      - db
    networks:
      - rinha2024q1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5431:5432"
    volumes:
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - rinha2024q1
    deploy:
      resources:
        limits:
          # Note que a soma de todos os limites dos serviços
          # aqui declarados é de 1.5 unidades de CPU e 550MB
          # de memória. A distribuição feita aqui é apenas
          # um exemplo – distribua como quiser.
          cpus: "0.2"
          memory: "140MB"

